version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: daphne -b 0.0.0.0 -p 8000 scoreboard.asgi:application
    volumes:
      - .:/app
      - ./data:/data  # SQLite 데이터베이스 파일이 저장될 디렉토리
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=mysecretkey
      - DATABASE_URL=sqlite:///data/db.sqlite3
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
