# Generated by Django 5.0.7 on 2024-08-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_team_pubdate_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.team"
                    ),
                ),
            ],
        ),
    ]
