# Generated by Django 5.0.7 on 2024-08-06 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_gamescore"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Member",
        ),
    ]
